export const ADD_GAMES = 'ADD_GAMES';
export const GAMES_LOADING = 'GAMES_LOADING';
export const GAMES_FAILED = 'GAMES_FAILED';

export const ADD_POSTS = 'ADD_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_TECHS = 'ADD_TECHS';
export const TECHS_LOADING = 'TECHS_LOADING';
export const TECHS_FAILED = 'TECHS_FAILED';